### ISSUE TITLE
merge_dates(other) - bad comparison?

### ISSUE THREAD

**Issue by mjy** [inukshuk/csl-ruby#4]
Not completely postive, but I think the == comparison here is incorrectly formatted now?

https://github.com/inukshuk/csl-ruby/blob/master/lib/csl/locale.rb#L488 

On that line date is an array with two values, not a hash with key :form?

**Comment by inukshuk** [comment]
That could very well be the case.

Could you add a unit test to verify this?

**Comment by mjy** [comment]
Resolved in #5
